version: '3'

services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: beer_db
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

volumes:
  mariadb_data:
