# Generated by Django 4.2.5 on 2023-09-10 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0003_menu_menuitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
