# # beer_app/urls.py

# from django.urls import path
# from .views import MenuItemRetrieveUpdateDestroyView, MenuItemViewSet, MenuRetrieveUpdateDestroyView, MenuViewSet

# urlpatterns = [
#     path('menu/', MenuViewSet.as_view(), name='menu-list-create'),
#     path('menu/<int:pk>/', MenuRetrieveUpdateDestroyView.as_view(), name='menu-detail'),
#     path('menuitem/', MenuItemViewSet.as_view(), name='menuitem-list-create'),
#     path('menuitem/<int:pk>/', MenuItemRetrieveUpdateDestroyView.as_view(), name='menu-detail'),
# ]


from django.urls import include, path
from rest_framework.routers import DefaultRouter
from .views import MenuViewSet, MenuItemViewSet

# Create a router for MenuViewSet and MenuItemViewSet
router = DefaultRouter()
router.register(r'menu', MenuViewSet)
router.register(r'menu-item', MenuItemViewSet)

urlpatterns = [
    # Include the URLs generated by the router
    path('', include(router.urls)),
]
